//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SOREVNOVANIA
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Entities1 : DbContext
    {
        public Entities1()
            : base("name=Entities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Accounting> Accounting { get; set; }
        public DbSet<Direction> Direction { get; set; }
        public DbSet<Group> Group { get; set; }
        public DbSet<Specialization> Specialization { get; set; }
        public DbSet<TypeCompetition> TypeCompetition { get; set; }
        public DbSet<sysdiagrams> sysdiagrams { get; set; }
    }
}
